language: node_js  #设置语言

node_js: stable  #设置相应的版本x

cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容

before_install:
    - export TZ='Asia/Shanghai' # 更改时区

install:
  - npm install  #安装hexo及插件

script:
  - hexo clean  #清除
  - hexo g  #生成

after_script:
  - git clone https://${gking_CO_REF} .deploy_git  # GH_REF是最下面配置的仓库地址
#- git clone https://${CO_REF} .deploy_git  # GH_REF是最下面配置的仓库地址
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./public/   # 这一步之前的操作是为了保留master分支的提交记录，不然每次git init的话只有1条commit
  - cd ./public
  - git config user.name "pond"  #修改name
  - git config user.email "greeedyboy@163.com"  #修改email
  - git add .
  - git commit -m "Builder at `date +"%Y-%m-%d %H:%M"`"  # 提交记录包含时间 跟上面更改时区配合ss
#  - git push --force --quiet "https://greeedyboy:${CO_TOKEN}@${CO_REF}" master:master  #GH_TOKEN是在Travis中配置token的名称
  - git push --force --quiet "https://pond:${Pond_CO_TOKEN}@${gking_CO_REF}" master:master  #GH_TOKEN是在Travis中配置token的名称
branches:
  only:
    - master  #只监测source分支，source是我的分支的名称，可根据自己情况设置
env:
 global:
   - gking_CO_REF: git.dev.tencent.com/pond/gking.git #设置GH_REF，注意更改yourname

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - greeedyboy@163.com
  on_success: change
  on_failure: always
