name: GitHub Actions Build and Deploy
on:
  issue_comment:
    types: [created, deleted]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: 1. git checkout...

      uses: actions/checkout@v1

    - name: 2. setup nodejs...

      uses: actions/setup-node@v1

    - name: 3. install hexo...

      run: |
        npm install hexo-cli -g
        npm i -S hexo-prism-plugin -g
        npm install hexo-generator-search --save -g
        npm i hexo-permalink-pinyin  -g
        npm i --save hexo-wordcount -g
        npm install hexo-filter-github-emojis  -g
        npm install hexo-generator-feed  -g
        npm install

    - name: 4. hexo generate public files...

      run: |
        hexo clean
        hexo g
    # 部署到腾讯云    

    - name: Deploy static to Tencent CloudBase

      run: |
        cd ./public_hrbeu
        git init
        git config user.name "pond"
        git config user.email "greeedyboy@163.com"
        git add .
        git commit -m "Builder at `date +"%Y-%m-%d %H:%M"`"
        git push --force --quiet "https://ZagYydJQqn:2028769833629d5eac0f86432d8b93572f4fc210@e.coding.net/pond/hrbeu.git" master:master
        
    - name: Get the deploy result

      run: echo "Deploy to cloudbase result ${{ steps.deployStatic.outputs.deployResult }}"
