# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    
    - name: 3. install hexo...
      run: |
        npm install hexo-cli -g
        npm i -S hexo-prism-plugin -g
        npm install hexo-generator-search --save -g
        npm i hexo-permalink-pinyin  -g
        npm i --save hexo-wordcount -g
        npm install hexo-filter-github-emojis  -g
        npm install hexo-generator-feed  -g
        npm install
    - name: 4. hexo generate public files...
    - run: hexo clean
    - run: hexo g        
    
    - name: Deploy static to Tencent CloudBase

      run: |
        cd ./public_sicau
        git init
        git config user.name "pond"
        git config user.email "greeedyboy@163.com"
        git add .
        git commit -m "Builder at `date +"%Y-%m-%d %H:%M"`"
        git push --force --quiet "https://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@github.com/greeedyboy/web_nankai.git"
